# UDP/TCP приём
source s_mikrotik_udp { syslog(transport(udp) ip(0.0.0.0) port(5140) so-rcvbuf(10485760)); };
source s_mikrotik_tcp { syslog(transport(tcp) ip(0.0.0.0) port(5140)); };

# Безопасный JSON через format-json
template t_json_safe {
  template("$(format-json \
              timestamp=$ISODATE \
              identity=${HOST} \
              host=$SOURCEIP \
              program=${PROGRAM} \
              level=${LEVEL} \
              message=${MESSAGE} \
            )\n");
};

# Пишем по устройствам и по дням:
destination d_mikrotik_per_host_daily {
  file("/var/log/mikrotik/complex_mikrotik.json"
       template(t_json_safe)
       create-dirs(yes) owner("root") group("adm") perm(0640));
};

log { source(s_mikrotik_udp); destination(d_mikrotik_per_host_daily); };
log { source(s_mikrotik_tcp); destination(d_mikrotik_per_host_daily); };
